### ISSUE TITLE
No bingo with free space

### ISSUE THREAD

**Issue by christopherpcline** [schrockwell/BruinsGo#2]
If you get a bingo using Jack's free square, the Bingo Jack pop up isn't activated, just noticed this after messing around with the new version. I like using Jack to mark the spaces but it makes it a bit harder to remember what that space was originally

**Comment by christopherpcline** [comment]
I also noticed that https://bekroogle.github.io/BruinsGo/ this version does work when using the free space, and I think that bingo pop up is much better for whatever it's worth.

**Comment by bekroogle** [comment]
Not anymore...I fetched upstream changes =].
